// Supabase configuration - generated from environment variables
// This file is typically generated by a build script, but we provide a TypeScript version

// These values should be injected at build time or loaded from environment
// For now, we'll set defaults that can be overridden
if (typeof window !== 'undefined') {
  (window as any).SUPABASE_URL = (window as any).SUPABASE_URL || 'https://kupggnglhxhglxapqfjl.supabase.co';
  (window as any).SUPABASE_ANON_KEY = (window as any).SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1cGdnbmdsaHhoZ2x4YXBxZmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMjE5NTQsImV4cCI6MjA3NzY5Nzk1NH0.ByKsNDoYo1-BzOkomADub6AknfrwwZ4PLaavNWgv_ho';
  (window as any).API_URL = (window as any).API_URL || 'http://localhost:3000/api';
}

export {};

