// Minimal .env injector for static sites: writes supabase-config.js from .env
// Usage: node inject-env.mjs
import fs from 'fs';
import path from 'path';
import url from 'url';

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Get project root (two levels up from backend/scripts/)
const projectRoot = path.resolve(__dirname, '../..');
const envPath = path.join(projectRoot, '.env');
const configPath = path.join(projectRoot, 'frontend/js/supabase-config.js');

function parseDotEnv(content) {
  const lines = content.split(/\r?\n/);
  const out = {};
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

if (!fs.existsSync(envPath)) {
  console.error('.env not found. Create a .env with SUPABASE_URL and SUPABASE_ANON_KEY.');
  process.exit(1);
}

const envContent = fs.readFileSync(envPath, 'utf8');
const env = parseDotEnv(envContent);

const urlVal = env.SUPABASE_URL || '';
const keyVal = env.SUPABASE_ANON_KEY || '';
const apiUrl = env.API_URL || 'http://localhost:3000/api';

if (!urlVal || !keyVal) {
  console.error('Missing SUPABASE_URL or SUPABASE_ANON_KEY in .env');
  process.exit(1);
}

const header = `// Generated by inject-env.mjs — do not edit manually\n`;
const body = `window.SUPABASE_URL = '${urlVal}';\nwindow.SUPABASE_ANON_KEY = '${keyVal}';\nwindow.API_URL = '${apiUrl}';\n`;

fs.writeFileSync(configPath, header + '\n' + body, 'utf8');
console.log('Updated supabase-config.js from .env');
console.log('API URL set to:', apiUrl);


