// Minimal .env injector for static sites: writes supabase-config.js from .env
// Usage: node inject-env.mjs
import fs from 'fs';
import path from 'path';
import url from 'url';
import dotenv from 'dotenv'; // Use installed dotenv package

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Get project root (two levels up from backend/scripts/)
const projectRoot = path.resolve(__dirname, '../..');
const envPath = path.join(projectRoot, '.env');
const configPath = path.join(projectRoot, 'frontend/js/supabase-config.js');

// Check if .env exists
if (!fs.existsSync(envPath)) {
  console.error('❌ .env not found. Please create one with SUPABASE_URL and SUPABASE_ANON_KEY.');
  process.exit(1);
}

// Load .env using dotenv
const result = dotenv.config({ path: envPath });

if (result.error) {
  console.error('❌ Error parsing .env file:', result.error);
  process.exit(1);
}

const env = process.env; // dotenv populates process.env

const urlVal = env.SUPABASE_URL;
const keyVal = env.SUPABASE_ANON_KEY;
// Default API URL if not set
const apiUrl = env.API_URL || 'http://localhost:3000/api';

// Validation
const errors = [];
if (!urlVal) errors.push('Missing SUPABASE_URL');
if (!keyVal) errors.push('Missing SUPABASE_ANON_KEY');

if (errors.length > 0) {
  console.error('❌ .env configuration incomplete:');
  errors.forEach(err => console.error(`   - ${err}`));
  console.error('Please check your .env file format.');
  process.exit(1);
}

// Validate URL format
try {
  new URL(urlVal);
} catch (e) {
  console.error(`❌ Invalid SUPABASE_URL: "${urlVal}"`);
  process.exit(1);
}

// Generate config file
const header = `// Generated by inject-env.mjs — do not edit manually\n`;
// JSON.stringify ensures safe string escaping
const body = `window.SUPABASE_URL = ${JSON.stringify(urlVal)};
window.SUPABASE_ANON_KEY = ${JSON.stringify(keyVal)};
window.API_URL = ${JSON.stringify(apiUrl)};
`;

fs.writeFileSync(configPath, header + body, 'utf8');
console.log('✅ Updated supabase-config.js from .env');
console.log(`   API URL: ${apiUrl}`);
console.log(`   Supabase URL: ${urlVal}`);
console.log('   Supabase Key: (Hidden)');


